---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: simple-web-server
  labels:
    app: sws
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sws
  template:
    metadata:
      labels:
        app: sws
    spec:
      containers:
      - name: simple-web-server-image
        # https://github.com/michalswi/simple-web-server
        image: michalsw/simple-web-server
        ports:
        - containerPort: 8080
        env:
        - name: SERVER_PORT
          value: "8080"
        readinessProbe:
          httpGet:
            path: "/"
            port: 8080
          initialDelaySeconds: 10
          timeoutSeconds: 5
---
apiVersion: v1
kind: Service
metadata:
  name: sws-service
spec:
  type: NodePort
  selector:
    app: sws
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8080
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress
  annotations:
    # gce-internal class deploys an internal HTTP(S) load balancer
    kubernetes.io/ingress.class: "gce-internal"
spec:
  rules:
  - http:
      paths:
      - path: /*
        pathType: ImplementationSpecific
        backend:
          service:
            name: sws-service
            port:
              number: 80
